### ISSUE TITLE
Help Menu

### ISSUE THREAD

**Issue by XenonDevZ** [saiteja-madha/discord-js-bot#199]
DiscordAPIError[10062]: Unknown interaction
    at SequentialHandler.runRequest (/home/container/node_modules/@discordjs/rest/dist/lib/handlers/SequentialHandler.cjs:293:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SequentialHandler.queueRequest (/home/container/node_modules/@discordjs/rest/dist/lib/handlers/SequentialHandler.cjs:99:14)
    at async REST.request (/home/container/node_modules/@discordjs/rest/dist/lib/REST.cjs:52:22)
    at async SelectMenuInteraction.deferUpdate (/home/container/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:192:5)
    at async InteractionCollector.<anonymous> (/home/container/src/commands/utility/help.js:151:5)
   
   I expected it to edit the embed, instead it sends 'You Are not the Author Of this button'

**Comment by XenonDevZ** [comment]
fixed
