### ISSUE TITLE
Erela

### ISSUE THREAD

**Issue by XenonDevZ** [saiteja-madha/discord-js-bot#200]
/home/container/node_modules/erela.js/dist/structures/Manager.js:102
                    throw new RangeError(`Plugin at index ${index} does not extend Plugin.`);
                    ^
RangeError: Plugin at index 0 does not extend Plugin.
    at new Manager (/home/container/node_modules/erela.js/dist/structures/Manager.js:102:27)
    at module.exports (/home/container/src/handlers/erela.js:34:17)
    at new BotClient (/home/container/src/structures/BotClient.js:66:59)
    at Object.<anonymous> (/home/container/bot.js:17:16)
    
    Im getting this error whenever I enable the music system

**Comment by TheGamer3514** [comment]
downgrade to node.js 17, reinstall packages then it should work
