### ISSUE TITLE
Can you help solve it?

### ISSUE THREAD

**Issue by ghost** [saiteja-madha/discord-js-bot#256]
C:\Users\usuario\OneDrive\Escritorio\discord-js-bot-5.1.0-scythe-new\discord-js-bot-5.1.0\src\database\schemas\Guild.js:18
  prefix: { type: String, default: PREFIX_COMMANDS.DEFAULT_PREFIX },
                                                   ^

TypeError: Cannot read properties of undefined (reading 'DEFAULT_PREFIX')
    at Object.<anonymous> (C:\Users\usuario\OneDrive\Escritorio\discord-js-bot-5.1.0-scythe-new\discord-js-bot-5.1.0\src\database\schemas\Guild.js:18:52)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (C:\Users\usuario\OneDrive\Escritorio\discord-js-bot-5.1.0-scythe-new\discord-js-bot-5.1.0\src\database\mongoose.js:22:12)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)

**Comment by saiteja-madha** [comment]
Make sure to use updated `config.js` file

**Comment by ghost** [comment]
Ok thank you @saiteja-madha
