### ISSUE TITLE
Error [InteractionNotReplied]

### ISSUE THREAD

**Issue by ArashSeyfi** [saiteja-madha/discord-js-bot#266]
This sometimes happens when the slash command is used
Error [InteractionNotReplied]: The reply to this interaction has not been sent or deferred.
    at ChatInputCommandInteraction.followUp (/home/ubuntu/NoobBot/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:177:64)
    at Object.handleSlashCommand (/home/ubuntu/NoobBot/src/handlers/command.js:192:25)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async module.exports (/home/ubuntu/NoobBot/src/events/interactions/interactionCreate.js:19:5)

**Comment by EditlT** [comment]
What's your code look like?

**Comment by saiteja-madha** [comment]
Can you provide the steps to replicate this? Or let us know when you faced the error?

**Comment by saiteja-madha** [comment]
Follow the steps in the docs and it should work. Alternatively, feel free to join our Discord server.
