### ISSUE TITLE
Guild Validation Failure

### ISSUE THREAD

**Issue by Legoman99573** [saiteja-madha/discord-js-bot#314]
**Describe the bug**
Occurs on guild validation. Once the bot is fully loaded, it will fail with the following error in **Additional context** section

**To Reproduce**
1. Startup the bot
2. Wait for everything to load
3. Error occurs

**Expected behavior**
Should validate the server guild and not show up.

**Screenshots**
![image](https://user-images.githubusercontent.com/7460704/219195643-20d3a911-5c56-4859-b617-1b556d176655.png)

**If possible**
 - NodeJS version: 18.14.0
 - Bot version: https://github.com/saiteja-madha/discord-js-bot/tree/v5.2.1
 - MongoDB Version: 6.0.4

**Additional context**
```applescript
ValidationError: guild validation failed: undefined: Cannot read properties of undefined (reading 'options')
    at Document.invalidate (/home/container/node_modules/mongoose/lib/document.js:3125:32)
    at _init (/home/container/node_modules/mongoose/lib/document.js:786:18)
    at init (/home/container/node_modules/mongoose/lib/document.js:737:5)
    at _init (/home/container/node_modules/mongoose/lib/document.js:760:7)
    at init (/home/container/node_modules/mongoose/lib/document.js:737:5)
    at Document.$__init (/home/container/node_modules/mongoose/lib/document.js:696:3)
    at model.syncWrapper [as $__init] (/home/container/node_modules/kareem/index.js:331:25)
    at Document.init (/home/container/node_modules/mongoose/lib/document.js:640:8)
    at Document.$init (/home/container/node_modules/mongoose/lib/document.js:656:42)
    at Object.createModelAndInit (/home/container/node_modules/mongoose/lib/queryhelpers.js:137:12)
    ```

**Comment by saiteja-madha** [comment]
Try using a new mongodb database

**Comment by Legoman99573** [comment]
Forgot I made this, but the issue was resolved. Thank you for the reply though.
