### ISSUE TITLE
bug /ticket setup

### ISSUE THREAD

**Issue by vexato** [saiteja-madha/discord-js-bot#329]
**Describe the bug**
C:\Users\vexato\Desktop\archive-2023-04-04T084424Z\node_modules\discord.js\src\client\actions\InteractionCreate.js:51
      if (channel && !channel.isTextBased()) return;
                              ^

TypeError: channel.isTextBased is not a function
    at InteractionCreateAction.handle (C:\Users\vexato\Desktop\archive-2023-04-04T084424Z\node_modules\discord.js\src\client\actions\InteractionCreate.js:51:31)
    at Object.module.exports [as INTERACTION_CREATE] (C:\Users\vexato\Desktop\archive-2023-04-04T084424Z\node_modules\discord.js\src\client\websocket\handlers\INTERACTION_CREATE.js:4:36)
    at WebSocketManager.handlePacket (C:\Users\vexato\Desktop\archive-2023-04-04T084424Z\node_modules\discord.js\src\client\websocket\WebSocketManager.js:352:31)
    at WebSocketShard.onPacket (C:\Users\vexato\Desktop\archive-2023-04-04T084424Z\node_modules\discord.js\src\client\websocket\WebSocketShard.js:489:22)
    at WebSocketShard.onMessage (C:\Users\vexato\Desktop\archive-2023-04-04T084424Z\node_modules\discord.js\src\client\websocket\WebSocketShard.js:328:10)
    at callListener (C:\Users\vexato\Desktop\archive-2023-04-04T084424Z\node_modules\ws\lib\event-target.js:290:14)
    at WebSocket.onMessage (C:\Users\vexato\Desktop\archive-2023-04-04T084424Z\node_modules\ws\lib\event-target.js:209:9)
    at WebSocket.emit (node:events:513:28)
    at Receiver.receiverOnMessage (C:\Users\vexato\Desktop\archive-2023-04-04T084424Z\node_modules\ws\lib\websocket.js:1178:20)
    at Receiver.emit (node:events:513:28)

**To Reproduce**
when I do the command /ticket setup and I click on the setup button this happens

**Screenshots**

**If possible**
 - NodeJS version: 18.15.0
 - Bot version:5.2.0
.

**Comment by AC1Studios** [comment]
Run `npm i discord.js@latest` to fix this issue

**Comment by vexato** [comment]
It's good how it works but I can't put the staff roles 

What should we put on?
Role ID or the name of the role for example@staff

**Comment by saiteja-madha** [comment]
Fixed as part of 5.3.0 release
