### ISSUE TITLE
error

### ISSUE THREAD

**Issue by AhmedElguker** [saiteja-madha/discord-js-bot#335]
/home/runner/discord-js-bot-2/node_modules/discord.js/src/client/actions/InteractionCreate.js:50
        if (channel && !channel.isTextBased()) return;
                                ^

TypeError: channel.isTextBased is not a function
    at InteractionCreateAction.handle (/home/runner/discord-js-bot-2/node_modules/discord.js/src/client/actions/InteractionCreate.js:50:33)
    at Object.module.exports [as INTERACTION_CREATE] (/home/runner/discord-js-bot-2/node_modules/discord.js/src/client/websocket/handlers/INTERACTION_CREATE.js:4:36)
    at WebSocketManager.handlePacket (/home/runner/discord-js-bot-2/node_modules/discord.js/src/client/websocket/WebSocketManager.js:352:31)
    at WebSocketShard.onPacket (/home/runner/discord-js-bot-2/node_modules/discord.js/src/client/websocket/WebSocketShard.js:489:22)
    at WebSocketShard.onMessage (/home/runner/discord-js-bot-2/node_modules/discord.js/src/client/websocket/WebSocketShard.js:328:10)
    at callListener (/home/runner/discord-js-bot-2/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onMessage (/home/runner/discord-js-bot-2/node_modules/ws/lib/event-target.js:209:9)
    at WebSocket.emit (node:events:390:28)
    at Receiver.receiverOnMessage (/home/runner/discord-js-bot-2/node_modules/ws/lib/websocket.js:1178:20)

**Comment by jerryzhangdev** [comment]
I got this error too, I fixed it by updating discord.js to version 14.8.0 in package.json and npm i

**Comment by rhaym-tech** [comment]
WOAH ITS A BIG BUG TO REPORT

**Comment by AC1Studios** [comment]
> I got this error too, I fixed it by updating discord.js to version 14.8.0 in package.json and npm i

that should help

**Comment by AhmedElguker** [comment]
> I got this error too, I fixed it by updating discord.js to version 14.8.0 in package.json and npm i

Thx It's work

**Comment by saiteja-madha** [comment]
Fixed as part of 5.3.0 release
