### ISSUE TITLE
Dashboard Not working 

### ISSUE THREAD

**Issue by ANIKETEDITZ** [saiteja-madha/discord-js-bot#358]
**When i try to use dashboard it doesn't load and sends error in console and discord channel**
```js
DiscordAPIError[50035]: Invalid Form Body
user_id[NUMBER_TYPE_COERCE]: Value "null" is not snowflake.
    at handleErrors (/home/runner/discord-js-bot/node_modules/@discordjs/rest/dist/index.js:640:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SequentialHandler.runRequest (/home/runner/discord-js-bot/node_modules/@discordjs/rest/dist/index.js:1021:23)
    at async SequentialHandler.queueRequest (/home/runner/discord-js-bot/node_modules/@discordjs/rest/dist/index.js:862:14)
    at async REST.request (/home/runner/discord-js-bot/node_modules/@discordjs/rest/dist/index.js:1387:22)
    at async UserManager.fetch (/home/runner/discord-js-bot/node_modules/discord.js/src/managers/UserManager.js:91:18)
    at async Object.fetchUser (/home/runner/discord-js-bot/dashboard/utils.js:34:16)
```

**Expected behavior**
The dashboard should load correctly

**Comment by rhaym-tech** [comment]
Use latest version, it would fix the problem

**Comment by ANIKETEDITZ** [comment]
Ok
