### ISSUE TITLE
this

### ISSUE THREAD

**Issue by rbbot2331** [saiteja-madha/discord-js-bot#359]
/home/runner/discord-bot-with-dashboard/node_modules/erela.js/dist/structures/Node.js:25
        throw new TypeError('Node option "host" must be present and be a non-empty string.');
        ^

TypeError: Node option "host" must be present and be a non-empty string.
    at check (/home/runner/discord-bot-with-dashboard/node_modules/erela.js/dist/structures/Node.js:25:15)
    at new Node (/home/runner/discord-bot-with-dashboard/node_modules/erela.js/dist/structures/Node.js:68:9)
    at new Manager (/home/runner/discord-bot-with-dashboard/node_modules/erela.js/dist/structures/Manager.js:85:17)
    at module.exports (/home/runner/discord-bot-with-dashboard/src/handlers/erela.js:34:17)
    at new BotClient (/home/runner/discord-bot-with-dashboard/src/structures/BotClient.js:66:59)
    at Object.<anonymous> (/home/runner/discord-bot-with-dashboard/bot.js:17:16)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)

**Comment by rhaym-tech** [comment]
Stupid ahh Replit error, please close this issue
Not related to us

**Comment by saiteja-madha** [comment]
> /home/runner/discord-bot-with-dashboard/node_modules/erela.js/dist/structures/Node.js:25 throw new TypeError('Node option "host" must be present and be a non-empty string.'); ^
> 
> TypeError: Node option "host" must be present and be a non-empty string. at check (/home/runner/discord-bot-with-dashboard/node_modules/erela.js/dist/structures/Node.js:25:15) at new Node (/home/runner/discord-bot-with-dashboard/node_modules/erela.js/dist/structures/Node.js:68:9) at new Manager (/home/runner/discord-bot-with-dashboard/node_modules/erela.js/dist/structures/Manager.js:85:17) at module.exports (/home/runner/discord-bot-with-dashboard/src/handlers/erela.js:34:17) at new BotClient (/home/runner/discord-bot-with-dashboard/src/structures/BotClient.js:66:59) at Object. (/home/runner/discord-bot-with-dashboard/bot.js:17:16) at Module._compile (node:internal/modules/cjs/loader:1101:14) at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10) at Module.load (node:internal/modules/cjs/loader:981:32) at Function.Module._load (node:internal/modules/cjs/loader:822:12)

Seems like you are passing an empty string for your lavalink host
