### ISSUE TITLE
I need help with api error

### ISSUE THREAD

**Issue by halvi07** [saiteja-madha/discord-js-bot#365]
DiscordAPIError[50035]: Invalid Form Body
embeds[0][LIST_ITEM_VALUE_REQUIRED]: List item values of ModelType are required
    at handleErrors (/home/container/node_modules/@discordjs/rest/dist/index.js:640:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SequentialHandler.runRequest (/home/container/node_modules/@discordjs/rest/dist/index.js:1021:23)
    at async SequentialHandler.queueRequest (/home/container/node_modules/@discordjs/rest/dist/index.js:862:14)
    at async REST.request (/home/container/node_modules/@discordjs/rest/dist/index.js:1387:22)
    at async TextChannel.send (/home/container/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:157:15)
    at async GuildChannel.safeSend (/home/container/src/helpers/extenders/GuildChannel.js:24:26)

**Comment by MSaeed-14** [comment]
What cmd did you run so that u got this error?

**Comment by halvi07** [comment]
I dont know, someone else uses it

**Comment by MSaeed-14** [comment]
People will need info to help you out

**Comment by saiteja-madha** [comment]
Need more information to resolve this
