### ISSUE TITLE
ERROR: Unhandled exception: Used disallowed intents

### ISSUE THREAD

**Issue by moibg** [saiteja-madha/discord-js-bot#457]
Error: Used disallowed intents
    at WebSocketShard.onClose (/home/container/node_modules/@discordjs/ws/dist/index.js:1132:18)
    at connection.onclose (/home/container/node_modules/@discordjs/ws/dist/index.js:676:17)
    at callListener (/home/container/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onClose (/home/container/node_modules/ws/lib/event-target.js:220:9)
    at WebSocket.emit (node:events:517:28)
    at WebSocket.emitClose (/home/container/node_modules/ws/lib/websocket.js:260:10)
    at TLSSocket.socketOnClose (/home/container/node_modules/ws/lib/websocket.js:1272:15)
    at TLSSocket.emit (node:events:529:35)
    at node:net:350:12
    at TCP.done (node:_tls_wrap:657:7)

**Comment by ghost** [comment]
got to the [developer portal](https://discord.com/developers/applications) click on ur bot and scroll a bit down click all the 3 sliders until they look like this:

![image](https://github.com/saiteja-madha/discord-js-bot/assets/122749762/7addf142-63fc-4a11-9f1a-a1f095cea4a9)
now retry and it should work!
LG
StrangeAPI

**Comment by saiteja-madha** [comment]
@StrangeAPI 
Your git repo makes use of this code without proper credits. Make sure to add proper credits to source
