### ISSUE TITLE
Channel not cached

### ISSUE THREAD

**Issue by saiteja-madha** [saiteja-madha/discord-js-bot#63]
```js
Error [CHANNEL_NOT_CACHED]: Could not find the channel where this message came from in the cache!
    at Message.edit (/home/strange/Desktop/discord-js-bot/node_modules/discord.js/src/structures/Message.js:653:46)
    at InteractionCollector.<anonymous> (/home/strange/Desktop/discord-js-bot/src/commands/utility/help.js:196:16)
    at InteractionCollector.emit (node:events:406:35)
    at InteractionCollector.stop (/home/strange/Desktop/discord-js-bot/node_modules/discord.js/src/structures/interfaces/Collector.js:197:10)
    at InteractionCollector._handleGuildDeletion (/home/strange/Desktop/discord-js-bot/node_modules/discord.js/src/structures/InteractionCollector.js:228:12)
    at BotClient.emit (node:events:406:35)
    at GuildDeleteAction.handle (/home/strange/Desktop/discord-js-bot/node_modules/discord.js/src/client/actions/GuildDelete.js:47:14)
    at Object.module.exports [as GUILD_DELETE] (/home/strange/Desktop/discord-js-bot/node_modules/discord.js/src/client/websocket/handlers/GUILD_DELETE.js:4:30)
    at WebSocketManager.handlePacket (/home/strange/Desktop/discord-js-bot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:350:31)
    at WebSocketShard.onPacket (/home/strange/Desktop/discord-js-bot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:443:22)
    at WebSocketShard.onMessage (/home/strange/Desktop/discord-js-bot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:300:10)
    at WebSocket.onMessage (/home/strange/Desktop/discord-js-bot/node_modules/ws/lib/event-target.js:199:18)
    at WebSocket.emit (node:events:394:28)
    at Receiver.receiverOnMessage (/home/strange/Desktop/discord-js-bot/node_modules/ws/lib/websocket.js:1022:20)
    at Receiver.emit (node:events:394:28)
    at Receiver.dataMessage (/home/strange/Desktop/discord-js-bot/node_modules/ws/lib/receiver.js:522:14)
```

**Comment by AstralRedshift** [comment]
I have the same problem, can you help me pls ?

**Comment by dmanexe** [comment]
Also having the same issue.

**Comment by dmanexe** [comment]
Update:

Isolated the code and found what triggered it for me, maybe this helps someone.

It appears that my issue was setting `message.channelId = foo` and `message.guildId = foo`, within another function.
