### ISSUE TITLE
TypeError: Cannot read property 'user' of undefined

### ISSUE THREAD

**Issue by saiteja-madha** [saiteja-madha/discord-js-bot#87]
**Describe the bug**
```js
TypeError: Cannot read property 'user' of undefined
    at /home/strange/Desktop/discord-js-bot/dashboard/app.js:33:30
    at Layer.handle [as handle_request] (/home/strange/Desktop/discord-js-bot/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/strange/Desktop/discord-js-bot/node_modules/express/lib/router/index.js:317:13)
    at /home/strange/Desktop/discord-js-bot/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/strange/Desktop/discord-js-bot/node_modules/express/lib/router/index.js:335:12)
    at next (/home/strange/Desktop/discord-js-bot/node_modules/express/lib/router/index.js:275:10)
    at session (/home/strange/Desktop/discord-js-bot/node_modules/express-session/index.js:196:71)
    at Layer.handle [as handle_request] (/home/strange/Desktop/discord-js-bot/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/strange/Desktop/discord-js-bot/node_modules/express/lib/router/index.js:317:13)
    at /home/strange/Desktop/discord-js-bot/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/strange/Desktop/discord-js-bot/node_modules/express/lib/router/index.js:335:12)
    at next (/home/strange/Desktop/discord-js-bot/node_modules/express/lib/router/index.js:275:10)
    at serveStatic (/home/strange/Desktop/discord-js-bot/node_modules/serve-static/index.js:75:16)
    at Layer.handle [as handle_request] (/home/strange/Desktop/discord-js-bot/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/strange/Desktop/discord-js-bot/node_modules/express/lib/router/index.js:317:13)
    at /home/strange/Desktop/discord-js-bot/node_modules/express/lib/router/index.js:284:7 
```

**If possible**
 - NodeJS version: 16.6.2
 - Bot version: 4.0.1

**Comment by saiteja-madha** [comment]
Fixed in v5
